name: Zicbot
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^10.1.0
  loading_animation_widget: ^1.2.0
  web_socket_channel: ^2.4.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0
  app_settings: ^5.1.1
  fl_chart: ^0.69.0
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.1
  flutter_local_notifications: ^19.4.1
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/zicboticon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
